### ISSUE TITLE
Kindle Previewer >= 3.82 support

### ISSUE THREAD

**Issue by yshalsager** [yshalsager/calibre-with-kfx#12]
Conversion fails starting from Kindle Previewer 3.82.2 (2024-05-27).

Log:

```
Converting to KFX
Software versions: KFX Output 2.8.0, calibre 7.13, Linux-6.5.0-1022-azure-x86_64-with-glibc2.36
KFX Output plugin help is available at http://www.mobileread.com/forums/showthread.php?t=272407

Converting trees.epub
Converting trees.epub to KPF
Preparing book trees.epub for conversion
Assuming UTF-8 encoding for c1.xhtml
Added XML declaration to c1.xhtml
Assuming UTF-8 encoding for c2.xhtml
Added XML declaration to c2.xhtml
Assuming UTF-8 encoding for titlepage.xhtml
Added XML declaration to titlepage.xhtml
Launching Kindle Previewer 3 (unknown_33511936) - CLI
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0048:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0048:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0048:err:systray:initialize_systray Could not create tray window
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: Unhandled page fault on write access to 0000000141EED000 at address 0000000[140](https://github.com/yshalsager/calibre-with-kfx/actions/runs/9722111925/job/26835624353#step:8:141)02030A (thread 0024), starting debugger...
011c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
011c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0114:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0114:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0114:fixme:dbghelp:elf_search_auxv can't find symbol in module

Process Failure: CLI return code 00000005
Traceback (most recent call last):
  File "runpy.py", line [198](https://github.com/yshalsager/calibre-with-kfx/actions/runs/9722111925/job/26835624353#step:8:199), in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/debug.py", line 289, in main
  File "calibre_plugins.kfx_output.__init__", line 265, in cli_main
  File "calibre_plugins.kfx_output.__init__", line 311, in convert_using_previewer
  File "calibre_plugins.kfx_output.__init__", line 357, in report_failure
Exception: Conversion error: Process Failure: CLI return code 00000005

****************** Conversion Failure Reason *****************
Process Failure: CLI return code 00000005
**************************************************************
Error: Process completed with exit code 1.
```

**Comment by emk2203** [comment]
Instead of running Kindle Previewer 3 with wine under linux in the container, could a workaround be to run real Windows in a VM in the container? Maybe [using winapps-org as the base](https://github.com/winapps-org/winapps)?

**Comment by yshalsager** [comment]
> Instead of running Kindle Previewer 3 with wine under linux in the container, could a workaround be to run real Windows in a VM in the container? Maybe [using winapps-org as the base](https://github.com/winapps-org/winapps)?

Interesting, not sure how easy will it to run things in cli the same way we do currently.

**Comment by yshalsager** [comment]
https://github.com/FreeRDP/FreeRDP/issues/2298

**Comment by emk2203** [comment]
Regarding this bug report of FreeRDP:

1. It's from 2015.
2. FreeRDP is obsolete. 

The one to use is `sdl-freerdp3`, from the `freerdp3` package (on Arch), [It has options for passing a command](https://manpages.ubuntu.com/manpages/oracular/man1/sdl-freerdp3.1.html):

>   /app:program:[path|||alias],cmd:command,file:filename,guid:guid,icon:filename,name:name,workdir:directory,hidef:[on|off]
           Remote application program

The newest version 3.9.0 may be the best option to get it to work

**Comment by CPeluti** [comment]
I don't know if using a windows container would be a great solution. One of the mains aspects that I see of the current approach using wine is the capability of just replicating the process withing other images like calibre-web or calibre-web-automated.

That said, the current dockerfile doesn't use a specific version of the Kindle Previewer, maybe it's a good idea to define explicitly.

**Comment by yshalsager** [comment]
fixed https://github.com/yshalsager/calibre-with-kfx/commit/58d6718aad5afad1b4b9a19e1eed6491922ec85e
